stages:
  - install_npm_dependencies
  - sonarcloud_analysis
  - docker_build
  - trivy_scan
  - push_to_Amazon_ECR
  - deploy_to_Amazon_ECS
      
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  GIT_DEPTH: "0"
  AWS_REGION: "AWS_DEFAULT_REGION"
  AWS_ACCESS_KEY: "AWS_ACCESS_KEY_ID"
  AWS_SECRET_KEY: "AWS_SECRET_ACCESS_KEY"

build_job: 
  stage: install_npm_dependencies
  tags: 
    - GitLab_EC2_Runner
  script:
    - sudo apt install nodejs -y
    - sudo apt install npm -y
    - sudo apt install docker.io -y && sudo chmod 666 /var/run/docker.sock
    - npm install

sonarcloud-check:
  stage: sonarcloud_analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - main

docker_build_job:
  stage: docker_build
  script: 
    - docker build -t gitlabcicd00:latest .
  only:
    - main
  tags:
    - GitLab_EC2_Runner

image_scan_job:
  stage: trivy_scan
  script: 
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.57.0 image gitlabcicd00:latest
  only:
    - main
  tags:
    - GitLab_EC2_Runner

push_image_to_ECR:
  stage: push_to_Amazon_ECR
  script: 
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 358966077154.dkr.ecr.us-east-1.amazonaws.com
    - docker tag gitlabcicd00:latest 358966077154.dkr.ecr.us-east-1.amazonaws.com/gitlabcicd00:latest
    - docker push 358966077154.dkr.ecr.us-east-1.amazonaws.com/gitlabcicd00:latest
  only:
    - main
  tags:
    - GitLab_EC2_Runner

deploy_image_to_ECS:
  stage: deploy_to_Amazon_ECS
  script: 
    - echo "Deploying to AWS ECS"
    - aws ecs update-service --cluster iquant-ecs --service iquant-ecs-svc --force-new-deployment --region $AWS_REGION
 only:
    - main
  tags:
    - GitLab_EC2_Runner



