   
stages:
  - install_npm_dependencies



build_job: 
  stage: install_npm_dependencies
  tags: 
    - GitLab_EC2_Runner
  script:
    - sudo apt install nodejs
    - sudo apt install npm 
    - npm install
